Django_Backend/fuelpricepredictor/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
]

Django_Backend/mainapp/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.login),
    path('login', views.login),
    path('register', views.register),
    path('create_profile', views.user_profile),
    path('edit_profile', views.user_profile),
    path('quote', views.fuel_quote),
    path('history', views.fuel_quote_history),
    path('logout', views.logout),
    path('suggested_price', views.suggested_price)
]

Django_Backend/mainapp/models.py
from django.db import models
from django.core.validators import MinLengthValidator
from django.utils import timezone


class UserCredentials(models.Model):
    userid = models.AutoField(primary_key=True)
    username = models.CharField(unique=True, max_length=20)
    password = models.CharField(
        validators=[MinLengthValidator(6)], max_length=20)
    confirm_password = models.CharField(
        validators=[MinLengthValidator(6)], max_length=20)

    updated_on = models.DateTimeField(auto_now=True)
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_on']

    def __unicode__(self):
        return self.username


class States(models.Model):
    stateid = models.AutoField(primary_key=True)
    code = models.CharField(validators=[MinLengthValidator(2)], max_length=2)
    name = models.CharField(max_length=50)

    class Meta:
        ordering = ['-code']


class ClientInformations(models.Model):
    userid = models.OneToOneField(
        UserCredentials, on_delete=models.CASCADE, primary_key=True)
    fullname = models.CharField(
        validators=[MinLengthValidator(1)], max_length=50)
    address1 = models.CharField(
        validators=[MinLengthValidator(1)], max_length=100)
    address2 = models.CharField(max_length=100)
    city = models.CharField(validators=[MinLengthValidator(1)], max_length=100)
    state = models.CharField(max_length=2)
    zipcode = models.CharField(
        validators=[MinLengthValidator(5)], max_length=9)
    updated_on = models.DateTimeField(auto_now=True)
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_on']

    def __unicode__(self):
        return self.fullname


class FuelQuotes(models.Model):
    quoteid = models.AutoField(primary_key=True)
    userid = models.ForeignKey(
        UserCredentials, on_delete=models.CASCADE)
    req_gallons = models.IntegerField()
    del_address = models.CharField(max_length=100)
    delivery_date = models.DateTimeField(auto_now=False)
    sugg_price = models.DecimalField(max_digits=9, decimal_places=3)
    due_amount = models.DecimalField(max_digits=9, decimal_places=3)
    updated_on = models.DateTimeField(auto_now=True)
    created_on = models.DateTimeField(auto_now_add=True,)

    class Meta:
        ordering = ['-created_on']


class Sessions(models.Model):
    userid = models.IntegerField(unique=True)
    status = models.BooleanField(default=False)
    updated_on = models.DateTimeField(auto_now=True)

Django_Backend/mainapp/forms.py
from django import forms
from .models import States


class LoginForm(forms.Form):
    username = forms.CharField(label='USER NAME', required=True,
                               widget=forms.TextInput(attrs={'placeholder': "User Name"}))

    password = forms.CharField(label='PASSWORD', required=True,
                               widget=forms.PasswordInput(attrs={'placeholder': "Passsword"}))


class RegisterForm(forms.Form):
    username = forms.CharField(label='USER NAME', required=True,
                               widget=forms.TextInput(attrs={'placeholder': "User Name"}))

    password = forms.CharField(label='PASSWORD', required=True,
                               widget=forms.PasswordInput(attrs={'placeholder': "Passsword"}))

    confirm_password = forms.CharField(label='CONFIRM PASSWORD', required=True,
                                       widget=forms.PasswordInput(attrs={'placeholder': "Confirm Passsword"}))


class UserProfileForm(forms.Form):
    OPTIONS = [('', 'Select State')]
    if(States):
        states = States.objects.all()
        for state in states:
            OPTIONS.append((state.code, state.name))

    fullname = forms.CharField(label='Full Name', required=False, max_length=50,
                               widget=forms.TextInput(attrs={'placeholder': "Full Name"}))

    address_1 = forms.CharField(label='Address 1', required=False, max_length=100,
                                widget=forms.TextInput(attrs={'placeholder': "Address 1"}))

    address_2 = forms.CharField(label='Address 2', required=False, max_length=100,
                                widget=forms.TextInput(attrs={'placeholder': "Address 2"}))

    city = forms.CharField(label='City', required=False, max_length=100,
                           widget=forms.TextInput(attrs={'placeholder': "City"}))

    state = forms.ChoiceField(
        required=False, choices=OPTIONS)

    zip = forms.CharField(label='Zip', required=False, max_length=9, min_length=5,
                          widget=forms.TextInput())


class FuelQuoteForm(forms.Form):

    gallonreq = forms.CharField(required=True,
                                widget=forms.NumberInput(attrs={'class': 'form-control', 'step': '1'}))

    deladdress = forms.CharField(required=False,
                                 widget=forms.TextInput(attrs={'disabled': 'disabled', 'class': 'form-control'}))

    deliverydate = forms.CharField(required=False,
                                   widget=forms.DateTimeInput(attrs={'class': 'form-control', 'type': 'date'}))

    suggprice = forms.CharField(required=False,
                                widget=forms.NumberInput(attrs={'disabled': 'disabled', 'class': 'form-control', 'step': 'any'}))

    deuamount = forms.CharField(required=False,
                                widget=forms.NumberInput(attrs={'disabled': 'disabled', 'class': 'form-control', 'step': 'any'}))

Django_Backend/mainapp/views.py
from datetime import datetime
from django.http import HttpResponseRedirect
from django.http import JsonResponse
from django.shortcuts import render
from django.contrib import messages
from .models import *
from .forms import LoginForm, RegisterForm, UserProfileForm, FuelQuoteForm
from .modules import Pricing


def login(request):
    initial_data = {'username': '', 'password': ''}

    if request.method == 'POST':
        form = LoginForm(request.POST)

        if form.is_valid() and is_username_valid(form.cleaned_data['username']) and is_password_valid(form.cleaned_data['password']):
            userexist = UserCredentials.objects.filter(
                username=form.cleaned_data['username'], password=form.cleaned_data['password']).exists()

            if userexist:
                user = UserCredentials.objects.get(
                    username=form.cleaned_data['username'])

                if Sessions.objects.filter(
                        userid=user.userid).exists():
                    session = Sessions.objects.get(userid=user.userid)
                    session.status = True
                    session.save()

                else:
                    session = Sessions(userid=user.userid, status=True)
                    session.save()

                request.session.flush()
                request.session['id'] = str(user.userid)
                return HttpResponseRedirect('/history')
            else:
                messages.error(request, "Invalid Username or Password!")
        else:
            messages.error(request, "Invalid Username or Password!")
    else:
        form = LoginForm(initial=initial_data)

    return render(request, 'login.html', {'form': form.as_p})


def logout(request):

    if request.method == 'GET':
        if (request.session.has_key('id')):
            user = UserCredentials.objects.get(
                userid=int(request.session['id']))

            if Sessions.objects.filter(
                    userid=user.userid).exists():
                session = Sessions.objects.get(userid=user.userid)
                session.status = False
                session.save()
            return HttpResponseRedirect('/login')
        else:
            return HttpResponseRedirect('/login')
    else:
        return HttpResponseRedirect('/login')


def register(request):
    initial_data = {'username': '',
                    'password': '', 'confirm_password': ''}
    if request.method == 'POST':
        form = RegisterForm(request.POST)

        if form.is_valid() and len(form.cleaned_data['password']) > 5 and form.cleaned_data['password'] == form.cleaned_data['confirm_password']:
            request.session['username'] = form.cleaned_data['username']
            request.session['password'] = form.cleaned_data['password']

            if (UserCredentials.objects.filter(username=request.session['username']).exists()):
                messages.error(
                    request, "Username already exists!")
            else:
                return HttpResponseRedirect('/create_profile')
        else:
            messages.error(
                request, "Short Password or Password did not match!")
    else:
        request.session.flush()
        form = RegisterForm(initial=initial_data)
    return render(request, 'register.html', {'form': form.as_p})


def user_profile(request):
    initial_data = {'fullname': '', 'address_1': '',
                    'address_2': '', 'city': '', 'state': '', 'zip': ''}

    if request.method == 'POST':

        form = UserProfileForm(request.POST)
        valid = form.is_valid()
        valid &= is_fullname_valid(form.cleaned_data['fullname'])
        valid &= is_address_valid(form.cleaned_data['address_1'])
        valid &= is_address2_valid(form.cleaned_data['address_2'])
        valid &= is_city_valid(form.cleaned_data['city'])
        valid &= is_state_valid(form.cleaned_data['state'])
        valid &= is_zip_valid(form.cleaned_data['zip'])

        if (valid):

            if request.session.has_key('id') and (ClientInformations.objects.filter(userid=int(request.session['id'])).exists()):
                user = int(request.session['id'])
                userinfo = ClientInformations.objects.get(userid=user)
                userinfo.fullname = form.cleaned_data['fullname']
                userinfo.address1 = form.cleaned_data['address_1']
                userinfo.address2 = form.cleaned_data['address_2']
                userinfo.city = form.cleaned_data['city']
                userinfo.state = form.cleaned_data['state']
                userinfo.zipcode = form.cleaned_data['zip']
                userinfo.save()
                return HttpResponseRedirect('/history')
            elif len(request.session['username']) > 0 and len(request.session['password']) > 0:
                username = request.session['username']

                if (UserCredentials.objects.filter(username=username).exists()):
                    user = UserCredentials.objects.get(username=username)
                    user.password = request.session['password']
                    user.confirm_password = request.session['password']
                    user.save()
                else:
                    user = UserCredentials(
                        username=request.session['username'],
                        password=request.session['password'],
                        confirm_password=request.session['password'])
                    user.save()
                request.session.flush()

                userinfo = ClientInformations(
                    userid=user,
                    fullname=form.cleaned_data['fullname'],
                    address1=form.cleaned_data['address_1'],
                    address2=form.cleaned_data['address_2'],
                    city=form.cleaned_data['city'],
                    state=form.cleaned_data['state'],
                    zipcode=form.cleaned_data['zip'])
                userinfo.save()
                return HttpResponseRedirect('/login')
        else:
            messages.error(request, "Please Check for invalid data/missing field")

    else:
        if request.session.has_key('username') and request.session.has_key('password'):
            form = UserProfileForm(initial=initial_data)
        elif request.session.has_key('id'):
            user = int(request.session['id'])
            session_exist = Sessions.objects.filter(
                userid=user, status=True).exists()
            if session_exist:
                userinfo = ClientInformations.objects.get(userid=user)
                initial_data['fullname'] = userinfo.fullname
                initial_data['address_1'] = userinfo.address1
                initial_data['city'] = userinfo.city
                initial_data['state'] = userinfo.state
                initial_data['zip'] = userinfo.zipcode
                form = UserProfileForm(initial=initial_data)
        else:
            return HttpResponseRedirect('/register')
    return render(request, 'user-profile.html', {'form': form.as_p})


def fuel_quote(request):
    if (request.session.has_key('id')):
        session = False
        user = int(request.session['id'])
        session_exist = Sessions.objects.filter(
            userid=user).exists()
        if session_exist:
            session = Sessions.objects.get(
                userid=user).status
            if session:
                userinfo = ClientInformations.objects.get(userid=user)
                username = UserCredentials.objects.get(userid=user).username
                state_name = States.objects.get(code=userinfo.state).name
                del_address = (userinfo.address1 + (', ' + userinfo.address2 if len(userinfo.address2) > 0 else '') + ', ' +
                               userinfo.city + ', ' + userinfo.zipcode + ', ' + state_name)
                # today = str(datetime.today().strftime('%Y-%m-%d'))
                data = {'gallonreq': '', 'deladdress': del_address,
                        'deliverydate': None, 'suggprice': '', 'deuamount': ''}

                if request.method == 'POST':
                    form = FuelQuoteForm(request.POST)

                    if form.is_valid() and int(form.cleaned_data['gallonreq']) > 0:
                        pricing = Pricing()
                        req_gallons = int(form.cleaned_data['gallonreq'])
                        sugg_price = pricing.get_suggested_price(
                            user, req_gallons)
                        sugg_price = round(sugg_price, 4)
                        amount_due = round((sugg_price * req_gallons), 4)
                        fuelquote = FuelQuotes(
                            userid=UserCredentials.objects.get(
                                userid=user),
                            req_gallons=req_gallons,
                            del_address=del_address,
                            delivery_date=datetime.strptime(
                                form.cleaned_data['deliverydate'], '%Y-%m-%d'),
                            sugg_price=sugg_price,
                            due_amount=amount_due)
                        fuelquote.save()
                        return HttpResponseRedirect('/history')
                    else:
                        messages.error(
                            request, "Data you entered is not valid!")

                else:
                    form = FuelQuoteForm(initial=data)

                return render(request, 'fuel-quote.html', {'form': form, 'loginuser': username, 'quote_active': True})
            else:
                return HttpResponseRedirect('/login')
        else:
            return HttpResponseRedirect('/login')
    else:
        return HttpResponseRedirect('/login')


def fuel_quote_history(request):
    if (request.session.has_key('id')):
        session = False
        user = int(request.session['id'])
        session_exist = Sessions.objects.filter(
            userid=user).exists()

Django_Backend/mainapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>Fuel Price Predictor</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="google" content="notranslate" />

    <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <link
      rel="shortcut icon"
      type="image/png"
      href="{% static 'img/favicon.ico' %}"
      />
    <link rel="stylesheet" href="{% static 'css/robotogooglefonts.css' %}" />
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/index.css' %}" />
  </head>

  <body>
    <div class="d-flex" id="wrapper">
      {% block sidebar %} {% include 'sidebar.html' %} {% endblock sidebar %}
      <div id="page-content-wrapper">
        <div class="container-fluid">
          {% block content %} {% endblock content %}
        </div>
        <div class="login-user">
          <div class="login-user-warpper">
            <div>
              <span>Logged in as {{loginuser}} </span>
            </div>
            <div class="edit-profile">
              <form action="/edit_profile" method="get">
                <button type="submit" class="logout-btn">Edit Profile</button>
              </form>
            </div>
            <div class="logout">
              <form action="/logout" method="get">
                <button type="submit" class="logout-btn">Logout</button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

Django_Backend/mainapp/templates/form-base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>Fuel Price Predictor</title>

    <meta name="google" content="notranslate" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <link
      rel="shortcut icon"
      type="image/png"
      href="{% static 'img/favicon.ico' %}"
    />
    <link rel="stylesheet" href="{% static 'css/robotogooglefonts.css' %}" />
    <link rel="stylesheet" href="{% static 'css/form.css' %}" />
  </head>
  <body>
    <div class="card">
      {% block content %} {% endblock content %}
    </div>
  </body>
</html>

Django_Backend/mainapp/templates/fuel-quote-history.html
{% extends "base.html" %} {% block content %}{% load mathfilters %}
<h2 class="page-heading">Fuel Quote History</h2>
<div class="main card">
  <table class="fuel-quote-history table table-striped">
    <thead>
      <tr>
        <th scope="col" style="width: 100px;">S.N.</th>
        <th scope="col" class="w-200">Gallons Requested</th>
        <th scope="col">Delivery Address</th>
        <th scope="col" class="w-150">Delivery Date</th>
        <th scope="col" class="text-right w-220">Suggested Price per Gallon</th>
        <th scope="col" class="text-right w-220">Total Amount Due</th>
      </tr>
    </thead>
    <tbody>
      {% if data %} {% for row in data %}
      <tr>
        <td scope="row">{{forloop.counter}}</td>
        <td class="w-200">{{row.req_gallons}}</td>
        <td>{{row.del_address}}</td>
        <td class="w-150">{{row.delivery_date}}</td>
        <td class="text-right w-220">{{row.sugg_price}}</td>
        <td class="text-right w-220">{{row.due_amount}}</td>
      </tr>
      {% endfor %} {% else %}
      <tr aria-colspan="6">
        <td colspan="6" class="text-center">No Record Found!</td>
      </tr>
      {% endif %}
    </tbody>
  </table>
</div>
{%endblock%}

Django_Backend/mainapp/templates/fuel-quote.html
{% extends "base.html" %} {% block content %}
<h2 class="page-heading">Fuel Quote</h2>
<div class="main card">
  {% if messages %}
  <div class="alert alert-danger">
    {% for message in messages %}
    <span>{{message}}</span>
    {% endfor %}
  </div>
  {% endif%}
  <form class="fuel-quote" action="/quote" method="post">
    {% csrf_token %}
    <div class="form-row">
      <div class="form-group col-md-6">
        <label for="id_gallonreq">Gallons Requested:</label>
        {{form.gallonreq}}
      </div>
      <div class="form-group col-md-6">
        <label for="id_deladdress">Delivery Address:</label>
        {{form.deladdress}}
      </div>
    </div>
    <div class="form-row">
      <div class="form-group col-md-6">
        <label for="id_deliverydate">Delivery Date:</label>
        {{form.deliverydate}}
      </div>
      <div class="form-group col-md-6">
        <label for="id_suggprice">Suggested Price per Gallon (USD):</label>
        {{form.suggprice}}
      </div>
    </div>
    <div class="form-row">
      <div class="form-group col-md-6"></div>
      <div class="form-group col-md-6">
        <label for="id_deuamount">Total Amount Due (USD):</label>
        {{form.deuamount}}
      </div>
    </div>
    <button
      type="button"
      disabled="disabled"
      id="get_quote"
      class="btn btn-primary"
    >
      Get Quote
    </button>
    <button
      type="submit"
      disabled="disabled"
      id="submit_quote"
      class="btn btn-primary"
    >
      Submit Quote
    </button>
    <p id="error_msg"></p>
  </form>
</div>
{% block javascript %}
<script>
  $("#get_quote").on("click", function () {
    $.ajax({
      url: "/suggested_price",
      data: {
        csrfmiddlewaretoken: "{{ csrf_token }}",
        gallon_req: $("#id_gallonreq").val(),
      },
      method: "post",
    })
      .done(function (data) {
        $("#id_suggprice").val(data["sugg_price"]);
        $("#id_deuamount").val(data["amount_due"]);
        $("#submit_quote").attr("disabled", false);
        $("#error_msg").html("");
        $("#error_msg").hide();
      })
      .fail(function () {
        $("#error_msg").html("Request Failed! Please try again!");
        $("#error_msg").show();
      });
  });

  $("#id_gallonreq").on("keyup", function () {
    if ($(this).val() > 0 && $("#id_deliverydate").val()) {
      $("#get_quote").attr("disabled", false);
    } else {
      $("#get_quote").attr("disabled", true);
    }
  });

  $("#id_deliverydate").on("change", function () {
    if ($("#id_gallonreq").val() > 0 && $(this).val()) {
      $("#get_quote").attr("disabled", false);
    } else {
      $("#get_quote").attr("disabled", true);
    }
  });
</script>
{% endblock %} {%endblock%}

Django_Backend/mainapp/templates/login.html
{% extends "form-base.html" %} {% block content %}

<div class="main">
  <form action="/login" method="post">
    <h1><span>User Login</span></h1>
    <div class="inset">
      {% if messages %}
      <div class="alert alert-danger">
        {% for message in messages %}
        <span>{{message}}</span>
        {% endfor %}
      </div>
      {% endif%} {% csrf_token %} {{form}}
      <!-- <span><a href="#">Forgot password ?</a></span> -->
    </div>

    <p class="p-container">
      <span class="link"><a href="register">Register Now</a></span>
      <input type="submit" value="Login" />
    </p>
  </form>
</div>

{%endblock%}

Django_Backend/mainapp/templates/register.html
{% extends "form-base.html" %} {% block content %}

<div class="main">
  <form action="/register" method="post">
    <h1><span>User Registration</span></h1>
    <div class="inset">
      {% if messages %}
      <div class="alert alert-danger">
        {% for message in messages %}
        <span>{{message}}</span>
        {% endfor %}
      </div>
      {% endif%} {% csrf_token %} {{form}}
    </div>

    <p class="p-container">
      <span class="link"><a href="login">Back</a></span>
      <input type="submit" value="Continue" />
    </p>
  </form>
</div>
{%endblock%}

Django_Backend/mainapp/templates/sidebar.html
{% block sidebar %}

<div class="bg-light border-right" id="sidebar-wrapper">
  <div class="sidebar-heading">Fuel Price Predictor</div>
  <div class="list-group list-group-flush">
    <a
      id="history"
      href="history"
      class="list-group-item list-group-item-action bg-light"
      >Fuel Quote History</a
    >
    <a
      id="quote"
      href="quote"
      class="list-group-item list-group-item-action bg-light"
      >Fuel Quote</a
    >
  </div>
  <footer class="py-3 bg-grey">
    <p class="m-0 text-dark text-center">
      Copyright &copy; Fuel Price Predictor {% now 'Y' %}
    </p>
  </footer>
</div>
<script>
  var url = window.location.href;
  if (url.indexOf("/history") > -1) {
    $("#quote").removeClass("active");
    $("#history").addClass("active");
  } else {
    $("#history").removeClass("active");
    $("#quote").addClass("active");
  }
</script>
{% endblock sidebar %}

Django_Backend/mainapp/templates/user-profile.html
{% extends "form-base.html" %} {% block content %}

<div class="main user-profile">
  <form action="create_profile" method="post">
    <h1><span>User Profile</span></h1>
    <div class="inset">
      {% if messages %}
      <div class="alert alert-danger">
        {% for message in messages %}
        <span>{{message}}</span>
        {% endfor %}
      </div>
      {% endif%} {% csrf_token %} {{form}}
    </div>
    <p class="p-container">
      <span class="link"><a href="register">Back</a></span>
      <input type="submit" value="Submit" />
    </p>
  </form>
</div>

{%endblock%}